version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/localconf.d:/etc/nginx/conf.d
        ports:
            - 8877:80
        depends_on:
            - app
        container_name: project_nginx
        restart: always

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: project_app
        depends_on:
            - db
        restart: always

    supervisor:
        build:
            context: .
            dockerfile: _docker/supervisor/Dockerfile
        container_name: project_supervisor
        volumes:
            - ./:/var/www
        restart: always

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db/:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: skaenergy
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8102:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: project_db

    phpmyadmin:
        image: arm64v8/phpmyadmin
        container_name: project_pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        restart: always
        ports:
            - 8080:80
        depends_on:
            - db
